name = "thetruth-subscribe"
main = "index.js"

compatibility_date = "2024-01-01"

routes = [
  { pattern = "thetruth.io.vn/api/subscribe/*", zone_name = "thetruth.io.vn" }
]

[[d1_databases]]
binding = "DB"
database_name = "thetruth-subscribers"
database_id = "575326b2-7326-46ef-9827-0622a61bfb46"

[[kv_namespaces]]
binding = "SUBSCRIBERS_KV"
id = "c7d23f66c10544878327f072448d2adf"

[vars]
SITE_URL = "https://thetruth.io.vn"
